### ISSUE TITLE
Lo intentamos sacar adelante?

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcas-s3-evaluacion-intermedia-Albametnet#1]
Sabrías hacerlo ahora?

1. Hay que pasar el array a App
2. Al menos hay que usar un map para convertirlo a array de jsx
3. Usemos UL y LI, y luego ya dentro, el div para cada card. Recuerda la jerarquía de encabezados

**Comment by Albametnet** [comment]
Hola Carlos, a ver que tal lo ves. He decidido hacerlo con App y un solo componente más. Esto lo he hecho así porque fue la idea principal que tuve durante el examen.
